version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: '09:00'
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10

  - package-ecosystem: 'pnpm'
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
      time: '09:00'
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
