name: Build
on:
  pull_request:
    branches:
      - feature/*
      - develop
      - main
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install packages
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run build
