name: Lint
on:
  pull_request:
    branches:
      - feature/*
      - develop
      - main
jobs:
  test:
    name: Check codestyle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Typecheck
        run: bun run typecheck

      - name: Prettier
        run: bun run lint:prettier

      - name: Eslint
        run: bun run lint:eslint

      - name: Secretlint
        run: bun run lint:secretlint

      - name: Ls lint
        run: bun run lint:ls-lint

      - name: Markup lint
        run: bun run lint:markup-lint

      - name: Ts prune
        run: bun run lint:ts-prune
