name: Lint
on:
  pull_request:
    branches:
    - feature/*
      - develop
      - main
jobs:
  test:
    name: Check codestyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install packages
        run: pnpm install --frozen-lockfile
      
      - name: Biome
        run: pnpm run lint:biome

      - name: Typecheck
        run: pnpm run typecheck

      - name: Secretlint
        run: pnpm run lint:secretlint

      - name: Ls lint
        run: pnpm run lint:ls-lint

      - name: Markup lint
        run: pnpm run lint:markup-lint

      - name: Ts prune
        run: pnpm run lint:ts-prune
